### ISSUE TITLE
Crypte's performance issue

### ISSUE THREAD

**Issue by asze17** [jay3332/rdenticon#1]
https://github.com/jay3332/rdenticon/blob/16d5bf0445c1b88bd891379027c14834f2601ec3/src/config.rs#L230-L250

As seen, yourself, jay3332, is using the write! macro but not using any format string, in this case, please use `fmt::Formatter::write_str`, thanks much.

**Comment by jay3332** [comment]
Ok Crypte

**Comment by jay3332** [comment]
Fixed in latest commit
