### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by asze17** [jay3332/rdenticon#2]
'ellipse must have non-zero radii, have you called .with_size() yet?', /home/codespace/.cargo/git/checkouts/ril-6598186e9c09ec68/629fc65/src/draw.rs:1419:9` yeah so somewhere in your code didn't call with_size

**Comment by jay3332** [comment]
Small sizes may cause.this error, try at least 32x32

**Comment by asze17** [comment]
@jay3332
